import { StyleSheet } from 'react-native';
import { colors } from './splashStyles';

export const onboardingStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 100,
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.onSurfaceVariant,
    marginBottom: -4,
  },
  stepBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: colors.primaryContainer + '1A',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryContainer + '33',
  },
  stepBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.05,
    textTransform: 'uppercase',
    color: colors.primary,
  },
  illustrationContainer: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 32,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '4D',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    alignSelf: 'center',
    marginBottom: 48,
    overflow: 'hidden',
  },
  illustration: {
    width: '100%',
    height: 280,
  },
  contentSection: {
    width: '100%',
    marginBottom: 24,
  },
  contentTitle: {
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 32,
    color: colors.onSurface,
    textAlign: 'center',
    marginBottom: 8,
  },
  contentBody: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: colors.onSurfaceVariant,
    textAlign: 'center',
  },
  highlight: {
    fontWeight: '700',
    color: colors.primary,
  },
  stepDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 24,
    marginBottom: 48,
  },
  dotActive: {
    width: 32,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  dotInactive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.outlineVariant,
  },
  actions: {
    width: '100%',
    marginTop: 'auto',
    paddingTop: 24,
  },
  nextButton: {
    width: '100%',
    backgroundColor: colors.primaryContainer,
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  nextButtonText: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.onPrimary,
  },
  skipButton: {
    width: '100%',
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  skipButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.05,
    textTransform: 'uppercase',
    color: colors.onSurfaceVariant,
  },
  decorativeBlur1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: colors.primary + '0D',
  },
  decorativeBlur2: {
    position: 'absolute',
    bottom: -40,
    left: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: colors.secondary + '0D',
  },
});
