import { StyleSheet } from 'react-native';
import { colors } from './splashStyles';

export const signupStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  logoSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  logo: {
    width: 140,
    height: 140,
    marginBottom: 0,
  },
  appName: {
    fontSize: 36,
    lineHeight: 44,
    fontWeight: '700',
    letterSpacing: -0.02,
    color: colors.onSurface,
  },
  tagline: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: colors.onSurfaceVariant,
    marginTop: -4,
  },
  card: {
    width: '100%',
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '4D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.04,
    shadowRadius: 50,
    elevation: 4,
  },
  cardTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.onSurface,
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 12,
  },
  label: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.05,
    textTransform: 'uppercase',
    color: colors.onSurfaceVariant,
    marginBottom: 4,
    marginLeft: 4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '66',
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  inputFocused: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: colors.onSurface,
  },
  passwordRow: {
    flexDirection: 'row',
    gap: 16,
  },
  passwordField: {
    flex: 1,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
    paddingVertical: 4,
    marginBottom: 16,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.outlineVariant,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: colors.onSurfaceVariant,
    flexShrink: 1,
  },
  checkboxLink: {
    color: colors.primary,
    fontWeight: '600',
  },
  createButton: {
    width: '100%',
    backgroundColor: colors.primaryContainer,
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: colors.primaryContainer,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 4,
  },
  createButtonText: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.onPrimaryContainer,
  },
  divider: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant + '4D',
    alignItems: 'center',
    gap: 12,
  },
  footerText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: colors.onSurfaceVariant,
  },
  signInLink: {
    color: colors.primary,
    fontWeight: '700',
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: 8,
  },
  socialButtonText: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: colors.onSurface,
  },
});
