import { StyleSheet } from 'react-native';
import { colors } from './splashStyles';

export const onboardingStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 100,
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  stepBadge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: colors.primary + '1A',
    borderRadius: 999,
    marginBottom: 8,
  },
  stepBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.05,
    color: colors.primary,
  },
  headerTitleLarge: {
    fontSize: 36,
    lineHeight: 44,
    fontWeight: '700',
    letterSpacing: -0.02,
    color: colors.onSurface,
    textAlign: 'center',
  },
  illustrationContainer: {
    width: '100%',
    maxWidth: 320,
    aspectRatio: 1,
    borderRadius: 24,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '4D',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    alignSelf: 'center',
    marginBottom: 48,
    overflow: 'hidden',
  },
  illustration: {
    width: '100%',
    height: 280,
  },
  decorativeBlur1: {
    position: 'absolute',
    top: -48,
    right: -48,
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: colors.primary + '0D',
  },
  decorativeBlur2: {
    position: 'absolute',
    bottom: -48,
    left: -48,
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: colors.secondary + '0D',
  },
  contentSection: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 24,
  },
  contentTitle: {
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 28,
    lineHeight: 34,
    color: colors.onSurface,
    textAlign: 'center',
    marginBottom: 8,
  },
  contentBody: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: colors.onSurfaceVariant,
    textAlign: 'center',
    maxWidth: 384,
  },
  stepDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 24,
    marginBottom: 48,
  },
  dotActiveWide: {
    width: 48,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  dotInactiveSmall: {
    width: 24,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.outlineVariant + '66',
  },
  actions: {
    width: '100%',
    marginTop: 'auto',
    paddingTop: 16,
    paddingBottom: 48,
  },
  nextButtonSolid: {
    width: '100%',
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 4,
  },
  nextButtonTextSolid: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    color: colors.onPrimary,
  },
});
