import { StyleSheet } from 'react-native';
import { colors } from './splashStyles';

export const onboardingStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 100,
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  headerLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.05,
    textTransform: 'uppercase',
    color: colors.primary,
    marginBottom: 4,
  },
  stepBadge: {
    alignItems: 'center',
  },
  stepBadgeText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: colors.outline,
  },
  stepIndicatorLine: {
    marginTop: 4,
    width: 24,
    height: 4,
    backgroundColor: colors.primary,
    borderRadius: 99,
    alignSelf: 'center',
  },
  illustrationContainer: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 24,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '4D',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    alignSelf: 'center',
    marginBottom: 24,
    overflow: 'hidden',
  },
  illustration: {
    width: '100%',
    height: '100%',
  },
  contentSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  contentTitle: {
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 32,
    color: colors.onSurface,
    textAlign: 'center',
    marginBottom: 8,
  },
  contentBody: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: colors.onSurfaceVariant,
    textAlign: 'center',
    maxWidth: 384,
  },
  actions: {
    width: '100%',
    marginTop: 'auto',
    paddingTop: 48,
    paddingBottom: 48,
  },
  continueButton: {
    width: '100%',
    backgroundColor: colors.primaryContainer,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 4,
  },
  continueButtonText: {
    fontWeight: '700',
    fontSize: 18,
    color: colors.onPrimary,
  },
});
