import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const colors = {
  tertiaryFixedDim: '#4cd7f6',
  outline: '#737686',
  onSurfaceVariant: '#434655',
  primaryFixedDim: '#b4c5ff',
  background: '#f8fafc',
  onPrimaryFixedVariant: '#003ea8',
  surfaceContainer: '#eceef0',
  surfaceContainerLow: '#f2f4f6',
  onTertiaryContainer: '#d7f6ff',
  onSecondaryFixed: '#0f0069',
  onTertiaryFixed: '#001f26',
  errorContainer: '#ffdad6',
  primary: '#004ac6',
  onSecondary: '#ffffff',
  error: '#ba1a1a',
  inversePrimary: '#b4c5ff',
  secondary: '#4b41e1',
  secondaryContainer: '#645efb',
  secondaryFixedDim: '#c3c0ff',
  onPrimaryContainer: '#eeefff',
  tertiary: '#005e6e',
  onSurface: '#191c1e',
  outlineVariant: '#c3c6d7',
  surfaceContainerLowest: '#ffffff',
  surfaceBright: '#f7f9fb',
  onPrimaryFixed: '#00174b',
  onError: '#ffffff',
  onErrorContainer: '#93000a',
  onBackground: '#191c1e',
  surfaceContainerHighest: '#e0e3e5',
  onPrimary: '#ffffff',
  secondaryFixed: '#e2dfff',
  primaryContainer: '#2563eb',
  surfaceContainerHigh: '#e6e8ea',
  primaryFixed: '#dbe1ff',
  onTertiary: '#ffffff',
  inverseSurface: '#2d3133',
  onSecondaryFixedVariant: '#3323cc',
  surfaceDim: '#d8dadc',
  inverseOnSurface: '#eff1f3',
  surfaceVariant: '#e0e3e5',
  tertiaryContainer: '#00788c',
  onTertiaryFixedVariant: '#004e5c',
  surface: '#f7f9fb',
  tertiaryFixed: '#acedff',
  surfaceTint: '#0053db',
  onSecondaryContainer: '#fffbff',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 48,
    maxWidth: 440,
    alignSelf: 'center',
    width: '100%',
  },
  topSection: {
    alignItems: 'center',
    marginTop: -30,
  },
  logo: {
    width: 140,
    height: 140,
    marginBottom: -10,
  },
  appName: {
    fontFamily: 'Poppins',
    fontWeight: '900',
    fontSize: 40,
    lineHeight: 44,
    color: colors.primary,
    letterSpacing: -0.5,
  },
  tagline: {
    fontFamily: 'Poppins',
    fontWeight: '500',
    fontSize: 18,
    color: colors.onSurfaceVariant,
    marginTop: 10,
  },
  card: {
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: 'rgba(195, 198, 215, 0.3)',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 4,
    width: '100%',
    marginTop: 70,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  cardIcon: {
    fontSize: 24,
    color: colors.primary,
  },
  cardTitle: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.05,
    textTransform: 'uppercase',
    color: colors.primary,
  },
  cardBody: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
    color: colors.onSurface,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 12,
  },
  avatarGroup: {
    flexDirection: 'row',
    marginRight: 8,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.surfaceContainerLowest,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  avatarFirst: {
    marginLeft: 0,
  },
  avatarIcon: {
    fontSize: 12,
  },
  badgeText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: colors.outline,
    marginLeft: 4,
  },
  bottomSection: {
    width: '100%',
    paddingBottom: 56,
  },
  button: {
    backgroundColor: colors.primaryContainer,
    borderRadius: 18,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 4,
     marginTop: 40,
  },
  buttonShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
  },
  buttonText: {
    fontFamily: 'Poppins',
    fontWeight: '700',
    fontSize: 18,
    color: colors.onPrimary,
  },
  buttonIcon: {
    fontSize: 20,
    color: colors.onPrimary,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 32,
    marginTop: 24,
  },
});
